/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        "4xl": "2rem",
        "5xl": "2.5rem",
        "6xl": "3rem",
        "7xl": "3.5rem",
        "8xl": "4rem",
        "9xl": "4.5rem",
      },
      animation: {
        "scale-up-tl": "scale-up-tl .3s cubic-bezier(.39,.575,.565,1.000) both",
        "scale-up-tr":
          "scale-up-tr .3s cubic-bezier(.39,.575,.565,1.000) both",
        "scale-up-center":
          "scale-up-center .3s cubic-bezier(.39,.575,.565,1.000) both",
        "scale-down-tl":
          "scale-down-tl .3s cubic-bezier(.39,.575,.565,1.000) both",
        "fade-in": "fade-in .6s cubic-bezier(.39,.575,.565,1.000) .1s both",
      },
      keyframes: {
        /* ----------------------------------------------
         * Generated by Animista on 2024-6-11 13:20:22
         * Licensed under FreeBSD License.
         * See http://animista.net/license for more info.
         * w: http://animista.net, t: @cssanimista
         * ---------------------------------------------- */

        "scale-up-tl": {
          "0%": {
            transform: "scale(0.5)",
            "transform-origin": 0,
          },
          "100%": {
            transform: "scale(1)",
            "transform-origin": 0,
          },
        },
        "scale-up-tr": {
        "0%": {
          transform: "scale(0.5)",
          "transform-origin": 0,
        },
        "100%": {
          transform: "scale(1)",
          "transform-origin": 0,
        },
        },
        "scale-up-center": {
          "0%": {
            transform: "scale(0.5)",
          },
          "100%": {
            transform: "scale(1)",
          },
        },
        "scale-down-tl": {
          "0%": {
            transform: "scale(1)",
            "transform-origin": 0,
          },
          "100%": {
            transform: "scale(0.5)",
            "transform-origin": 0,
          },
        },
        "fade-in": {
          "0%": {
            opacity: 0,
          },
          "100%": {
            opacity: 1,
          },
        },
      },
    },
  },
  plugins: [],
};
